title: Artificial Intelligence for robots and swarms
baseurl: http://opentechschool-brussels.github.io/AI-for-robots-and-swarms

markdown: redcarpet
redcarpet:
   extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "strikethrough", "autolink"]

pygments: true

permalink: title.html
